linters-settings:
  govet:
    check-shadowing: true

linters:
  enable:
    - govet
    - golint
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck

run:
  deadline: 1m