services:
  development:
    image: mcr.microsoft.com/vscode/devcontainers/universal:latest
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
  mysql-database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db_data: