name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.5

    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go mod download

    - name: Run tests
      run: go test -v ./...

  validate-docs:
    name: Validate the docs
    runs-on: ubuntu-latest
    steps:

    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Download validate-markdown-docs
      run: git clone -b 0.1.0 https://github.com/adamsc64/validate-markdown-docs /tmp/validate-markdown-docs

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2'

    - name: Validate the docs
      run: |
        cd /tmp/validate-markdown-docs
        ./validate-markdown-docs ${{ github.workspace }}
