name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  project-unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.3

    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Get dependencies
      run: go mod download

    - name: Run tests with coverage
      run: go test -v -coverprofile=coverage.out ./...

    - name: Generate coverage HTML report
      run: go tool cover -html=coverage.out -o coverage.html

    - name: Upload coverage HTML report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-html-report
        path: coverage.html