name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  project-unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2.2.0
      with:
        go-version: 1.21.5

    - name: Check out the repository
      uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0

    - name: Get dependencies
      run: go mod download

    - name: Run tests
      run: go test -v ./...
