name: Validate Markdown Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-docs:
    name: Validate Markdown Docs
    runs-on: ubuntu-latest
    steps:

    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Download validate-markdown-docs
      run: git clone -b 0.1.0 https://github.com/adamsc64/validate-markdown-docs /tmp/validate-markdown-docs

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2'

    - name: Validate the docs
      run: |
        cd /tmp/validate-markdown-docs
        ./validate-markdown-docs ${{ github.workspace }}
